name = "Radio-T"
license = "Common Creative"
licenselink = "https://github.com/Azeeson/radio-t/LICENSE"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "https://radio-t.com/"
tags = ["podcast"]
features = ["menu", "sidebar", "podcast"]
min_version = 0.14

[author]
    name = "Azeeson"
    homepage = "https://github.com/Azeeson/radio-t"

# If Porting existing theme
[original]
    author =  ""
    homepage = ""
    repo = ""
